AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String

Resources:

  CFNTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-cfn-runtime-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

Outputs:

  BucketName:
    Value: !Ref CFNTemplatesBucket
    Export:
      Name: !Sub "${ProjectName}-cfn-bucket"