AWSTemplateFormatVersion: '2010-09-09'
Description: EFS for Jenkins Home on ECS Fargate

Parameters:
  ProjectName:
    Type: String

Resources:
  JenkinsEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: Name
          Value: !Sub "${ProjectName}-jenkins-efs"

Outputs:
  EFSFileSystemId:
    Value: !Ref JenkinsEFS
    Export:
      Name: !Sub "${ProjectName}-EFSId"
