name: Deploy Jenkins Infra

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Deploy Network + EFS Sequentially
      run: |

        echo "Deploying Network..."

        aws cloudformation deploy \
          --stack-name jenkins-network \
          --template-file cf-templates/network.yaml \
          --parameter-overrides file://variables/base-params.json

        echo "Waiting for Network..."

        aws cloudformation wait stack-create-complete \
          --stack-name jenkins-network || \
        aws cloudformation wait stack-update-complete \
          --stack-name jenkins-network

        echo "Network Ready"

        echo "Deploying EFS..."

        aws cloudformation deploy \
          --stack-name jenkins-efs \
          --template-file cf-templates/efs.yaml \
          --parameter-overrides file://variables/base-params.json

        echo "Waiting for EFS..."

        aws cloudformation wait stack-create-complete \
          --stack-name jenkins-efs || \
        aws cloudformation wait stack-update-complete \
          --stack-name jenkins-efs

        echo "EFS Ready"